<?php

  require 'vendor/autoload.php';

  use Mpdf\Config\ConfigVariables;
  use Mpdf\Config\FontVariables;
  use Mpdf\Mpdf;
  use Mpdf\MpdfException;

  include "connect.php";
  include "auth_engine.php";
  include "query-helper.php";

  date_default_timezone_set("Asia/Dhaka");

  const LIMIT_ADDER = 0;

  // Help: https://mpdf.github.io/fonts-languages/fonts-in-mpdf-7-x.html
  /**
   * @throws MpdfException
   */
  function getBanglaMPDF($user): Mpdf {
    $header1 = "নারায়ণগঞ্জ সিটি কর্পোরেশন"; // Medium Size;
    $header2 = "নারায়ণগঞ্জ"; // Small Size;
    $header3 = "ফ্যামিলি কার্ডধারী পরিবারের তালিক"; // Large Size;

    $defaultConfig = (new ConfigVariables())->getDefaults();
    $fontDirs = $defaultConfig["fontDir"];

    $defaultFontConfig = (new FontVariables())->getDefaults();
    $fontData = $defaultFontConfig["fontdata"];

    $mpdf = new Mpdf([
      "fontDir" => array_merge($fontDirs, ["fonts/"]),
      "fontdata" => $fontData + [
          "bangla" => [
            "R" => "Bangla.ttf",
            "B" => "Bangla.ttf",
            "I" => "Bangla.ttf",
            "BI" => "Bangla.ttf",
            "useOTL" => 0xFF,
          ],
          "kalpurush" => [
            "R" => "Kalpurush.ttf",
            "B" => "Kalpurush.ttf",
            "I" => "Kalpurush.ttf",
            "BI" => "Kalpurush.ttf",
            "useOTL" => 0xFF,
          ],
          "vrinda" => [
            "R" => "Vrinda.ttf",
            "B" => "Vrinda.ttf",
            "I" => "Vrinda.ttf",
            "BI" => "Vrinda.ttf",
            "useOTL" => 0xFF,
          ],
        ],
      "format" => "A4",
      "orientation" => "L",
      "setAutoTopMargin" => "stretch",
      "setAutoBottomMargin" => "stretch",
    ]);

    $headerArray = [
      "C" => [
        "content" =>
          "<div class='pdf-header-container'>" .
          "<h4>$header1</h4>" .
          "<h3>$header2</h3>" .
          "<h2>$header3</h2>" .
          "</div>",
        "font-size" => 10,
        "font-family" => "bangla",
      ],
      "line" => 1,
    ];

    $footerArray = [
      "L" => [
        "content" =>
          "Report generated by: $user[name]",
        "font-size" => 10,
        "font-family" => "freesans",
      ],
      "C" => [
        "content" =>
          date("h:i:s A | l, F d, Y"), // date("h:i:s A | l, F d, Y", strtotime("now +3 GMT"))
        "font-size" => 10,
        "font-family" => "freesans",
      ],
      "R" => [
        "content" =>
          "Page {PAGENO} of {nbpg}",
        "font-size" => 10,
        "font-family" => "freesans",
      ]
    ];

    $mpdf->SetHeader($headerArray, 'O');
    $mpdf->SetFooter($footerArray, "O");

    return $mpdf;
  }

  function downloadPDF($projectID, $offset, $limit): void {
    global $conn, $user, $beneficiaryKeys;
    $sqlGetProject = "SELECT * FROM project WHERE ID=$projectID";

    if ($rowProject = mysqli_fetch_assoc(mysqli_query($conn, $sqlGetProject))) {
      $sqlVerifyModerator = "SELECT * FROM project_moderators WHERE Moderator_ID=$user[id] AND Project_ID=$projectID";
      $filename = $rowProject["Name"] . " - Downloaded by $user[name] on " . date("F d, Y");

      if (mysqli_num_rows(mysqli_query($conn, $sqlVerifyModerator))) {
        // Moderator Verified
        $offset = preg_match("/\d+/", $offset)? intval($offset) - 1 : 0;
        $limit = preg_match("/\d+/", $limit)? intval($limit) : 1000;
        $limit += LIMIT_ADDER;
        $cnt = $offset + 1;

        try {
          $pdf = getBanglaMPDF($user);
          $pdf -> SetTitle($filename);

          $sqlGetBeneficiaries = "SELECT * FROM beneficiary WHERE Project_ID=$projectID ORDER BY Created_on LIMIT $offset, $limit";
          $resultBeneficiaries = mysqli_query($conn, $sqlGetBeneficiaries);

          $htmlDoc =
            "<!DOCTYPE html>" .
            "<html lang=\"en\">" .
            "<head>" .
            "<link rel=\"stylesheet\" href=\"css/project.css\">" .
            "<style>" .
            "body {" .
            "display: flex;" .
            "flex-direction: column;" .
            "}" .
            ".beneficiaries-table-pdf th, .beneficiaries-table-pdf td {" .
            "padding: 5px;" .
            "}" .
            ".beneficiaries-table-pdf  {" .
            "width: 100%;" .
            "border-spacing: 0;" .
            "}" .
            ".beneficiaries-table-pdf, .beneficiaries-table-pdf td, .beneficiaries-table-pdf th {" .
            "border: 1px solid black;" .
            "border-spacing: 0;" .
            "}" .
            "</style>" .
            "</head>" .
            "<body>";

          $beneficiaryTable =
            "<table class='beneficiaries-table-pdf'>" .
            getBeneficiaryTableHeader() .
            "<tbody>";

          $widths = [4, 10, 6, 10, 10, 10, 10, 10, 10, 10, 10];

          while ($rowBeneficiary = mysqli_fetch_assoc($resultBeneficiaries)) {
            $beneficiary = decode(...getMapValues($rowBeneficiary, $beneficiaryKeys));

            $beneficiaryTable .= "<tr><td style='text-align: center; font-family: kalpurush, serif; font-size: 15px;'>" . engToBanglaNumeric($cnt) . "</td>";
            $i = 1;

            foreach ($beneficiary as $beneficiaryAttribute) {
              $beneficiaryTable .= "<td style='text-align: center; font-family: kalpurush, serif; font-size: 15px; width: $widths[$i]%;'>$beneficiaryAttribute</td>";
              $i++;
            }

            $beneficiaryTable .= "</tr>";

            $cnt++;
          }

          $beneficiaryTable .= "</tbody></table>";

          $htmlDoc .= $beneficiaryTable . "</body></html>";

          for ($i = 0; $i < strlen($htmlDoc); $i += 1000000) {
            $pdf->WriteHTML(substr($htmlDoc, $i, 1000000));
          }

          clearDir("generated-files/pdf/", 10);

          $pdf->Output("generated-files/pdf/" . $filename . ".pdf", "F");


          echo createJSON(1, "generated-files/pdf/" . $filename . ".pdf");
        } catch (Exception $ex) {
          echo createJSON(2, $ex->getMessage());
        }
      } else {
        echo createJSON(2, "You do not have access to this project.");
      }
    } else {
      echo createJSON(2, "Project does not exist");
    }
  }

  function downloadTextFile($projectID, $delimiter="\t", $offset="0", $limit="1000", $headerRowsCount=0, $headerColumnsCount=0, $fileType="tsv"): void {
    global $conn, $user, $beneficiaryKeys, $utf8BOM;
    $sqlGetProject = "SELECT * FROM project WHERE ID=$projectID";

    if ($rowProject = mysqli_fetch_assoc(mysqli_query($conn, $sqlGetProject))) {
      $sqlVerifyModerator = "SELECT * FROM project_moderators WHERE Moderator_ID=$user[id] AND Project_ID=$projectID";
      $filename = $rowProject["Name"] . " - Downloaded by $user[name] on " . date("F d, Y");

      if (mysqli_num_rows(mysqli_query($conn, $sqlVerifyModerator))) {
        // Moderator Verified
        $offset = preg_match("/\d+/", $offset)? intval($offset) - 1 : 0;
        $limit = preg_match("/\d+/", $limit)? intval($limit) : 1000;
        $limit += LIMIT_ADDER;
        $cnt = $offset + 1;

        try {
          $sqlGetBeneficiaries = "SELECT * FROM beneficiary WHERE Project_ID=$projectID ORDER BY Created_on LIMIT $offset, $limit";
          $resultBeneficiaries = mysqli_query($conn, $sqlGetBeneficiaries);
          $filePath = "generated-files/$fileType/";
          $fileContent = "";
          if ($headerRowsCount > 0) $fileContent .= implode($delimiter, ["ক্রঃ নংঃ", "সিটি কর্পোরেশন", "ওয়ার্ড নম্বর", "বাড়ী বা মহল্লা", "উপকারভোগীর নাম", "এনআইডি নম্বর", "মোবাইল নম্বর", "জন্ম তারিখ (যদি থাকে)", "পেশা", "স্বামী বা স্ত্রীর এনআইডি", "অবিবাহিত হলে পিতার এনআইডি"]);
          if ($headerRowsCount > 1) $fileContent .= "\n" . implode($delimiter, array_map(fn($sn): string => engToBanglaNumeric($sn), range(1, 11)));

          while ($rowBeneficiary = mysqli_fetch_assoc($resultBeneficiaries)) {
            $beneficiary = decode(...getMapValues($rowBeneficiary, $beneficiaryKeys));
            if ($headerColumnsCount > 0) $beneficiary = array_merge([engToBanglaNumeric($cnt)], $beneficiary);

            $fileContent .= "\n" . implode($delimiter, $beneficiary);

            $cnt++;
          }

          $fileContent = trim($fileContent);

          clearDir($filePath, 10);
          if (file_put_contents($filePath . $filename . "." . $fileType, $utf8BOM . $fileContent)) {
            echo createJSON(1, [
              "filename" => $filename,
              "url" => $filePath . $filename . "." . $fileType,
            ]);
          } else {
            echo createJSON(2, strtoupper($fileType) . " file generation failed.");
          }
        } catch (Exception $ex) {
          echo createJSON(2, $ex->getMessage());
        }
      } else {
        echo createJSON(2, "You do not have access to this project.");
      }
    } else {
      echo createJSON(2, "Project does not exist");
    }
  }

  function downloadTSV($projectID, $offset="0", $limit="1000"): void {
    downloadTextFile($projectID, "\t", $offset, $limit, 0, 0, "tsv");
  }

  function downloadCSV($projectID, $offset="0", $limit="1000"): void {
    downloadTextFile($projectID, ", ", $offset, $limit, 2, 1, "csv");
  }

  if (isset($conn)) {
    $authUser = authenticate();
    if ($authUser["code"] == 1) {
      $user = $authUser["data"];
      if (isset($_POST["submit"])) {
        $method = "";
        $args = [];
        if (isset($_POST["method"])) $method = $_POST["method"];
        if (isset($_POST["args"])) $args = $_POST["args"];

        switch ($method) {
          case "downloadPDF":
            downloadPDF(...$args);
            break;
          case "downloadTSV":
            downloadTSV(...$args);
            break;
          case "downloadCSV":
            downloadCSV(...$args);
            break;
          default:
            echo json_encode(array(
              "code" => 502,
              "data" => "Unknown error occurred"
            ));
            break;
        }
      }
    } else {
      echo json_encode($authUser);
    }
  } else {
    echo json_encode(array(
      "code" => 2,
      "data" => "Database connection parameters missing."
    ));
  }
